version: '3'

services:
    mitmproxy:
        image: mitmproxy/mitmproxy
        ports:
        - "9080:9080"
        - "9081:9081"
        command: ["mitmweb", "--web-host", "0.0.0.0", "--web-port", "9080", "--listen-port", "9081"]

    db:
        image: mysql:5.7
        volumes:
        - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
        - db
        - mitmproxy
        build:
            dockerfile: Dockerfile.wordpress
            context: .
        volumes:
        - ./:/var/www/html/wp-content/plugins/cloudflare
        ports:
        - "9999:80"
        restart: always
        environment:
            # HTTP_PROXY: mitmproxy:9081
            # HTTPS_PROXY: mitmproxy:9081
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_CONFIG_EXTRA: |
               define('WP_HOME', 'http://wordpress.lol:9999' );
               define('WP_SITEURL', 'http://wordpress.lol:9999' );
               define('CLOUDFLARE_EMAIL', 'myemail@mail.com');
               define('CLOUDFLARE_API_KEY', 'sj7RQrrRxD1ED5W312NVoDpJIOd7XbFgpEM7zTRa');
               define('CLOUDFLARE_DOMAIN_NAME', 'mywebsite.com');

    adminer:
        image: adminer
        restart: always
        ports:
        - 9010:8080
        depends_on:
        - db

volumes:
    db_data: {}
